#@TYPE: Machine
#@NAME: i.MX 8MP Consolidated Machine For Matter
#@DESCRIPTION: A consolidated machine for i.MX 8MP LPDDR4 FRDM Matter demos
#@MAINTAINER: Lei Xu <lei.xu@nxp.com>

MACHINEOVERRIDES =. "imx8mp-lpddr4-frdm:"
require conf/machine/imx8mp-lpddr4-frdm.conf

DELTA_KERNEL_DEFCONFIG="${WORKDIR}/kernel-config/*"
IMAGE_INSTALL:append = " packagegroup-nxp-matter-baseline packagegroup-nxp-openthread packagegroup-nxp-otbr packagegroup-nxp-zigbee-rcp "

UBOOT_DELTA_CONFIG="${WORKDIR}/uboot-config/*"
