#@TYPE: Machine
#@NAME: A consolidated IW610 MATTER machine for FRDM-IMX91S
#@SOC: IMX91
#@MAINTAINER: Lei Xu <lei.xu@nxp.com>

MACHINEOVERRIDES =. "imx91-11x11-lpddr4-frdm-imx91s:"
require conf/machine/imx91-11x11-lpddr4-frdm-imx91s.conf

DELTA_KERNEL_DEFCONFIG="${WORKDIR}/kernel-config/*"

UBOOT_DELTA_CONFIG="${WORKDIR}/uboot-config/*"

IMAGE_INSTALL:append = " packagegroup-nxp-matter-baseline packagegroup-nxp-openthread packagegroup-nxp-otbr "
