# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-openhd"
BBFILE_PATTERN_meta-openhd = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-openhd = "6"

LAYERDEPENDS_meta-openhd = "core"
LAYERSERIES_COMPAT_meta-openhd = "kirkstone scarthgap"

# Prevent linux-imx customizations from affecting kirkstone-based BSPs
BBMASK:append:kirkstone = "|linux-imx_%.bbappend"

# Add build timestamp file into the FAT32 boot partition for i.MX8MP FRDM images.
WKS_FILE_DEPENDS:append:imx8mp-lpddr4-frdm = " openhd-buildinfo"
IMAGE_BOOT_FILES:append:imx8mp-lpddr4-frdm = " config.txt"
