# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have a packages directory, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "imx-frdm-release"
BBFILE_PATTERN_imx-frdm-release := "^${LAYERDIR}/"
BBFILE_PRIORITY_imx-frdm-release = "8"
LAYERSERIES_COMPAT_imx-frdm-release = "scarthgap"

# Overrides for imx93-11x11-lpddr4x-frdm.conf
MACHINE_FEATURES:append:imx93-11x11-lpddr4x-frdm = " dpdk nxpwifi-all-sdio"
MACHINE_FIRMWARE:append:imx93-11x11-lpddr4x-frdm = " ethos-u-firmware"
WKS_FILE_DEPENDS:append:imx93-11x11-lpddr4x-frdm = " imx-m33-demos"
IMAGE_BOOT_FILES:append:imx93-11x11-lpddr4x-frdm = " \
    imx93-11x11-evk_m33_TCM_power_mode_switch.bin \
    imx93-11x11-evk_m33_TCM_rpmsg_lite_pingpong_rtos_linux_remote.bin \
    imx93-11x11-evk_m33_TCM_rpmsg_lite_str_echo_rtos.bin \
"
IMXBOOT_TARGETS:imx93-11x11-lpddr4x-frdm = "${@bb.utils.contains('UBOOT_CONFIG', 'ecc', '${IMXBOOT_TARGETS_ECC}', '${IMXBOOT_TARGETS_SD}', d)}"

# Overrides for imx8mp-lpddr4-frdm
MACHINE_FEATURES:append:imx8mp-lpddr4-frdm = " optee nxpwifi-all-pcie nxpwifi-all-sdio dpdk"
WKS_FILE_DEPENDS:append:imx8mp-lpddr4-frdm = " imx-m7-demos"
IMAGE_BOOT_FILES:append:imx8mp-lpddr4-frdm = " \
    imx8mp_m7_TCM_hello_world.bin \
    imx8mp_m7_TCM_low_power_wakeword.bin \
    imx8mp_m7_TCM_rpmsg_lite_pingpong_rtos_linux_remote.bin \
    imx8mp_m7_TCM_rpmsg_lite_str_echo_rtos.bin \
    imx8mp_m7_TCM_sai_low_power_audio.bin \
"
