#@TYPE: Machine
#@NAME: i.MX 8MP Consolidated Machine
#@DESCRIPTION: A consolidated machine configuration for i.MX 8MP FRDM LPDDR4, see Important Note below
#@MAINTAINER: Lei Xu <lei.xu@nxp.com>

#        ** Important Note **
# This machine generates an image contain the bootloader of LPDDR4 FRDM, Kernel, and rootfs, plus the DTBs of
# LPDDR4 FRDM. The resulting image can be used for LPDDR4 FRDM directly.

MACHINEOVERRIDES =. "imx8mp-lpddr4-frdm:"
require conf/machine/imx8mp-lpddr4-frdm.conf
