#@TYPE: Machine
#@NAME: FRDM-IMX91S
#@SOC: IMX91
#@DESCRIPTION: A Consolidated machine configuration for FRDM-IMX91S, see Important Note below
#@MAINTAINER: Lei Xu <lei.xu@nxp.com>

#        ** Important Note **
# This machine generates images containing the bootloader of FRDM-IMX91S, Kernel, and rootfs, DTBs.
# The resulting image can be used for 11x11 LPDDR4 FRDM-IMX91S directly,
# For most users, the dedicated machine imx91-11x11-lpddr4-frdm-imx91s.conf should be used for simplicity.

MACHINEOVERRIDES =. "imx91-11x11-lpddr4-frdm-imx91s:"
require conf/machine/imx91-11x11-lpddr4-frdm-imx91s.conf
