#@TYPE: Machine
#@NAME: i.MX 91 Consolidated rootfs machine
#@SOC: i.MX91
#@DESCRIPTION: A Consolidated machine configuration for i.MX 91 LPDDR4 FRDM, see Important Note below
#@MAINTAINER: Lei Xu <lei.xu@nxp.com>

#        ** Important Note **
# This machine generates an image contain the bootloader of 11x11 LPDDR4 FRDM, Kernel, and rootfs, DTBs.
# The resulting image can be used for 11x11 LPDDR4 FRDM directly,
# For most users, the dedicated machine imx91-11x11-lpddr4-frdm.conf should be used for simplicity.

MACHINEOVERRIDES =. "imx91-11x11-lpddr4-frdm:"
require conf/machine/imx91-11x11-lpddr4-frdm.conf
